version: '3.8'

services:
  fastapi:
    build:
      context: ./api
      dockerfile: Dockerfile
    volumes:
      - ./asi-kedro:/asi-kedro
      - ./ml_models:/ml_models
    ports:
      - "12345:12345"

  streamlit:
    build:
      context: ./ui
      dockerfile: Dockerfile
    ports:
      - "8501:8501"
    depends_on:
      - fastapi