version: '3.8'

services:
  fastapi:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "12345:12345"

  streamlit:
    build:
      context: ./ui
      dockerfile: Dockerfile
    ports:
      - "8501:8501"
    depends_on:
      - fastapi